http {
    server {
        listen      $PORT;
        server_name _;

        location /_astro/ {
            proxy_pass http://localhost:4321;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $host;
            proxy_connect_timeout 300;
            proxy_send_timeout 300;
            proxy_read_timeout 300;
            proxy_buffering off;
            proxy_request_buffering off;
        }

        location /alpha/ {
            # This rule removes the /alpha prefix before sending to the container.
            # e.g., /alpha/embed.js becomes /embed.js
            # e.g., /alpha/9hhmb5fufv becomes /9hhmb5fufv
            rewrite ^/alpha/(.*)$ /$1 break;

            proxy_pass http://localhost:4321;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $host;
            proxy_connect_timeout 300;
            proxy_send_timeout 300;
            proxy_read_timeout 300;
            proxy_buffering off;
            proxy_request_buffering off;
        }

        # Static files from file-server
        location /static/ {
            proxy_pass http://localhost:$FILE_SERVER_PORT;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $host;
        }

        # (Fallback): All other requests go to the main backend server.
        location / {
            proxy_pass http://localhost:$API_SERVER_PORT;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $host;
            # Add timeout configurations
            proxy_connect_timeout 300;
            proxy_send_timeout 300;
            proxy_read_timeout 300;
            proxy_buffering off;
            proxy_request_buffering off;
        }
    }
}

